---

- name: Prep CentOS
  hosts: all
  become: yes
  tasks:
  - import_tasks: update-hosts.yaml
  - import_tasks: update-centos.yaml
  - import_tasks: prep-all.yaml

- name: Prep Master
  hosts: masters
  become: yes
  gather_facts: no
  tasks:
  - import_tasks: prep-master.yaml
