---

- name: Update All Packages
  yum:
    name: "*"
    update_cache: yes
    state: latest
  register: reboot_node

- name: Reboot system if required
  when: reboot_node is changed
  reboot:
    post_reboot_delay: 180
    reboot_timeout: 900
