apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-blue
  namespace: f5demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: node-blue
    spec:
      containers:
      - image: "chen23/f5-demo-app:openshift"
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "Node Blue (No SSL)"
        - name: F5DEMO_NODENAME_SSL
          value: "Node Blue (SSL)"
        - name: F5DEMO_COLOR
          value: "0000FF"
        - name: F5DEMO_COLOR_SSL
          value: "0000FF"
        imagePullPolicy: IfNotPresent
        name: node-blue
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: node-blue
  labels:
    run: node-blue
  namespace: f5demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 8443
    protocol: TCP
    targetPort: 8443
    name: https
  type: ClusterIP
  selector:
    run: node-blue

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-green
  namespace: f5demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: node-green
    spec:
      containers:
      - image: "chen23/f5-demo-app:openshift"
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "Node Green (No SSL)"
        - name: F5DEMO_COLOR
          value: "99FF99"
        - name: F5DEMO_NODENAME_SSL
          value: "Node Green (SSL)"
        - name: F5DEMO_COLOR_SSL
          value: "00FF00"
        imagePullPolicy: IfNotPresent
        name: node-green
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: node-green
  labels:
    run: node-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  type: ClusterIP
  selector:
    run: node-green
